services:
  php:
    build:
      context: .
    volumes:
      - ./example-app:/var/www/example-app
    ports:
      - "8800:8800"
    command: php artisan serve --host=0.0.0.0 --port=8800
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
